# hydra:
  # verbose: true
  # output_subdir: null  
  # run:
  #   dir: .


defaults: # last one wins
- _self_
- data: data
- model: ENet
- version: v0.0.1
- model_version: ${model}_${version}
- override hydra/job_logging: custom
