hydra:
  # verbose: true
  # output_subdir: null  
  # run:
  #   dir: .

defaults: # last one wins
  - _self_
  - cfg_folder_1: option_1
  - cfg_folder_2: option_1
  - override hydra/job_logging: custom
  - env_variables: env_1
