hydra:
  # verbose: true
  # output_subdir: null  
  # run:
  #   dir: .

defaults: # last one wins
- _self_
- data: data
- model/ENet/ENet
- env_variables: env_1
- override hydra/job_logging: custom
