default_language_version:
  python: python3.10

exclude: poetry.lock

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.3
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.3
  hooks:
  - id: ruff-format

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix, --indent, '2']
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
